export const currencyList = [
  { code: "USD", label: "US Dollar" },
  { code: "EUR", label: "Euro" },
  { code: "GBP", label: "British Pound" },
  { code: "INR", label: "Indian Rupee" },
  { code: "JPY", label: "Japanese Yen" },
  { code: "AUD", label: "Australian Dollar" },
  { code: "CAD", label: "Canadian Dollar" },
  { code: "CHF", label: "Swiss Franc" },
  { code: "CNY", label: "Chinese Yuan" },
  { code: "HKD", label: "Hong Kong Dollar" },
  { code: "NZD", label: "New Zealand Dollar" },
  { code: "SGD", label: "Singapore Dollar" },
  { code: "SEK", label: "Swedish Krona" },
  { code: "NOK", label: "Norwegian Krone" },
  { code: "MXN", label: "Mexican Peso" },
  { code: "ZAR", label: "South African Rand" },
  { code: "BRL", label: "Brazilian Real" },
  { code: "RUB", label: "Russian Ruble" },
  { code: "KRW", label: "South Korean Won" },
  { code: "THB", label: "Thai Baht" },
  { code: "AED", label: "UAE Dirham" },
  { code: "SAR", label: "Saudi Riyal" },
  { code: "TRY", label: "Turkish Lira" },
  { code: "PLN", label: "Polish Zloty" },
  { code: "IDR", label: "Indonesian Rupiah" },
  { code: "VND", label: "Vietnamese Dong" },
  { code: "PHP", label: "Philippine Peso" },
  { code: "EGP", label: "Egyptian Pound" },
  { code: "PKR", label: "Pakistani Rupee" },
  { code: "BDT", label: "Bangladeshi Taka" },
  { code: "LKR", label: "Sri Lankan Rupee" },
  { code: "KES", label: "Kenyan Shilling" },
  { code: "NGN", label: "Nigerian Naira" },
  { code: "ARS", label: "Argentine Peso" },
  { code: "DZD", label: "Algerian Dinar" },
  { code: "MAD", label: "Moroccan Dirham" },
  { code: "TWD", label: "New Taiwan Dollar" },
  { code: "CZK", label: "Czech Koruna" },
  { code: "HUF", label: "Hungarian Forint" },
  { code: "ILS", label: "Israeli New Shekel" },
  { code: "MYR", label: "Malaysian Ringgit" },
  { code: "QAR", label: "Qatari Riyal" },
  { code: "OMR", label: "Omani Rial" },
  { code: "BHD", label: "Bahraini Dinar" },
  { code: "JOD", label: "Jordanian Dinar" },
  { code: "KWD", label: "Kuwaiti Dinar" },
  { code: "CLP", label: "Chilean Peso" },
  { code: "COP", label: "Colombian Peso" },
  { code: "PEN", label: "Peruvian Sol" },
  { code: "UYU", label: "Uruguayan Peso" },
  { code: "UAH", label: "Ukrainian Hryvnia" },
  { code: "RON", label: "Romanian Leu" },
  { code: "DKK", label: "Danish Krone" },
  { code: "ISK", label: "Icelandic Krona" },
  { code: "HRK", label: "Croatian Kuna" },
  { code: "BGN", label: "Bulgarian Lev" }
];

// Sorting by label alphabetically:
const sortedCurrencyList = currencyList.sort((a, b) =>
  a.label.localeCompare(b.label)
);

console.log(sortedCurrencyList);
